spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:port/wecoding?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 60000
      connection-test-query: SELECT 1
      auto-commit: true
      idle-timeout: 50000

  messages:
    basename: i18n.login
  mail:
    host: smtp.qq.com
    username: you@email.com
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  redis:
    host: ip
    port: port
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        max-idle: 50
        min-idle: 1
        max-wait: 6000

  rabbitmq:
    host: 39.106.85.24
    username:
    password:
    port:

#  data:
#    elasticsearch:
#      cluster-nodes: 192.168.1.107:9300
#      cluster-name: elasticsearch

logging:
  config: classpath:spring-logback.xml
  pattern:
    console: "%d - %msg%n"
  level:
    root: info
#server:
#  servlet:
#    context-path:  /wecoding
